# Loads a local text file and allows you to do ChatGPT queries against it using langchain libraries
# Make sure to upgrade OpenAI, Langchain packages. Requires chromadb as well. e.g pip install openai chromadb --upgrade
# Privacy policy https://openai.com/policies/privacy-policy
# As of June 23/23 "OpenAI does not use data submitted to and generated by our API to train OpenAI models or improve OpenAI’s service offering"

import sys

from langchain.indexes import VectorstoreIndexCreator
from langchain.document_loaders import TextLoader

# if using directory loader
# from langchain.document_loaders import DirectoryLoader


from langchain.llms import OpenAI
from langchain.chat_models import ChatOpenAI

# Following two lines of code only needed for remote upload or if system variable for OpenAI API key is not set

# import constants
# os.environ["OPENAI_API_KEY"] = constants.APIKEY

query = sys.argv[1]

# Loader can be from multiple sources: unstructured data, dbs, remote webpages, entire directories
loader = TextLoader('data.txt')

# Sample loader for directories
# loader = DirectoryLoader(".", glob="*.txt")

# The data has to be split and indexed so the OpenAI engine can use it
index = VectorstoreIndexCreator().from_loaders([loader])

print(index.query(query))

# If you want it to have access to ChatGPT's data use this instead
# print(index.query(query, llm=ChatOpenAI()))